### ISSUE TITLE
Logs and reports for config issues

### ISSUE THREAD

**Issue by RaNd250** [Willena/OpenDNSUpdater#14]
Thanks for the app, but still haven't got it configured, and i dont know if is username/pass issue or something else. Some logings/reporting would be nice.

Also the "<-" back button is not working, only Android "back" button is.

**Comment by Willena** [comment]
Hi ! 

Thanks for using my app and reporting an issue !
I'll try to fix the "back" button in the next version.  

Can you give me more information on the android os and the app version you are using ? 

A few words on the credentials, try them on https://login.opendns.com/?return_to=https%3A%2F%2Fdashboard.opendns.com%2F if they are not working on the opendns website, you might need to reset your password or to create an account. Also do not forget to specify the network name. In my case the network name created on my personal the dashboard is "Home" and is configured inside the app as you can see.
![image](https://user-images.githubusercontent.com/1786065/50784676-a8603e80-12ae-11e9-9362-b4f8948dd301.png)
![screenshot_opendnsupdater_20190107-191813](https://user-images.githubusercontent.com/1786065/50785509-2e7d8480-12b1-11e9-964e-e0ba37605000.png)

If you want your IP address to be updated in opendns service, You need at least these "switch" configuration: 
![inkedscreenshot_opendnsupdater_20190107-191127_li](https://user-images.githubusercontent.com/1786065/50785281-6df7a100-12b0-11e9-99a8-81cb86260a41.jpg)

There are a lot of things that need to be done, especially to be more user friendly (having more useful texts, slides to configure the app for the first time and or create the opendns account, ...) I'm working on it but slowly since it is on my free time....
