### ISSUE TITLE
Add a way to enable or disable the app.

### ISSUE THREAD

**Issue by Willena** [Willena/OpenDNSUpdater#2]
## A little summary of the global idea of this issue

- [x] Give the possibility to choose networks where the update is not applied.
- [x] Give the possibility to totally disable the app.

**Comment by TPS** [comment]
I'm not sure whether this belongs here, or needs its own issue:  It'd be amazing if this app [could be background-free](https://greenify.uservoice.com/knowledgebase/articles/1177546-which-apps-should-i-greenify), since it only needs to do anything whenever the device IP address changes, which is 1× per network connection change, AFAIK.

N.B.: I believe any Android (e.g., a [Project Fi](http://nicholasarmstrong.com/2015/08/network-handover-google-fi/) or [Republic Wireless](https://help.republicwireless.com/hc/en-us/articles/115006311188-Adaptive-Coverage) devices) should be able to have _@ least_ 3 active IPv4/IPv6 addresses simultaneously: @ least 1 apiece per each active wifi's ___&___ SIM's data connections

**Comment by Willena** [comment]
@TPS The title and content of the issue were not very clear. I've updated them. 
The current app is background free. It only react on the network_change event generated by Android.

**Comment by TPS** [comment]
@Willena Current means the [currently unreleased `master` branch here](https://github.com/Willena/OpenDNSUpdater/compare/v1.0...master), I assume?  According to Greenify, [v1.0](https://github.com/Willena/OpenDNSUpdater/releases/download/v1.0/openDNSUpdater-v1.0.apk) isn't background-free.…

**Comment by Willena** [comment]
@TPS You're right, that's the version I was talking about.
By background-free I was thinking about services running in the background. In that case, the app has no service running in the background. But it may be possible that I do not completely close the app (aka the main activity) when you use it.

Definitely something that can be improved.
(https://stackoverflow.com/questions/3105673/how-to-kill-an-application-with-all-its-activities)

**Comment by Willena** [comment]
Since d8e8057 this is issue can be closed
